### ISSUE TITLE
Missing zero termination in WIC64_CMD_GET_SSID when SSID len is 32 characters

### ISSUE THREAD

**Issue by ra1fh** [WiC64-Team/wic64-firmware#10]
https://github.com/WiC64-Team/wic64-firmware/blob/54405a5aa5f7280a7cb5eabc7eda590c3c1509c6/wic64/connection.cpp#L118-L120

You probably want to add ssid[MAX_SSID_LEN] = '\0' here, or copy MAX_SSID_LEN + 1 characters. With an SSID of 32 characters and WiC firmware version 2.0.1, WIC64_CMD_GET_SSID returns 33 characters response payload. The last character of the response is 0xff in my case. That should probably be 0x00 instead.

Connecting to a 32 character SSID works fine btw.

**Comment by hbekel** [comment]
You're right of course, thanks for reporting this. 

I will publish a fix in the unstable version 2.0.1-2 via the WiC64 portal firmware update tool soon. A new stable version will be published once I have fixed a few more smaller issues.

**Comment by hbekel** [comment]
I have now also fixed the string termination for MAC and IP in 2.0.1-3 in a similar fashion.

**Comment by ra1fh** [comment]
Many thanks!
